name: Daily list Update

on:
  schedule:
  - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: Update list
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Script
        run: node compile-filters.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add adblock-list-regroup.txt README.md
          COMMIT_MESSAGE=$(cat commit-message.txt)
          git commit -m "$COMMIT_MESSAGE"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
